CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'main') THEN
        CREATE SCHEMA main;
    END IF;
END $EF$;

CREATE TABLE main.address (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    address_line1 text NOT NULL,
    address_line2 text,
    city text NOT NULL,
    state text NOT NULL,
    zip_code text NOT NULL,
    country text NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    CONSTRAINT "PK_address" PRIMARY KEY (id)
);

CREATE TABLE main."user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_name text NOT NULL,
    password text NOT NULL,
    email text NOT NULL,
    address_id bigint NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    CONSTRAINT "PK_user" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241206192834_FullElixiaDb', '9.0.0');

COMMIT;

